version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    target-branch: develop
    schedule:
      interval: 'daily'

  # Maintain dependencies for java
  - package-ecosystem: 'maven'
    directory: '/'
    target-branch: develop
    schedule:
      interval: 'daily'
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
